{% set name = "delayed-assert" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/delayed_assert-{{ version }}.tar.gz
  sha256: 0e1c65afae4bae9c57b91c76e38287562924c9964a58c309249790c725c46239

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - delayed_assert
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pr4bh4sh/python-delayed-assert
  summary: Delayed/soft assertions for python
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
